import { prisma } from '@zenowethu/database';
import { logger } from '@zenowethu/shared-lib';
import { stepRegistry } from '../step-registry';
import type { ActionContext } from '../step-registry';
import type { StepExecutionResult } from '../types';

interface LineItem {
  description: string;
  quantity: number;
  unitPrice: number;
}

stepRegistry.register(
  'GENERATE_INVOICE',
  async (ctx: ActionContext): Promise<StepExecutionResult> => {
    try {
      const { caseId, caseRecord, actionParams } = ctx;

      const lineItems: LineItem[] = (actionParams.lineItems as LineItem[]) || [
        {
          description: (actionParams.description as string) || 'Debt Counselling Service Fee',
          quantity: 1,
          unitPrice: Number(actionParams.amount || 0),
        },
      ];

      const subtotal = lineItems.reduce((sum, item) => sum + item.quantity * item.unitPrice, 0);
      const vatRate = 0.15;
      const vatAmount = subtotal * vatRate;
      const total = subtotal + vatAmount;

      const invoiceNumber = `INV-${Date.now()}-${caseRecord.fileNumber.replace(/[^A-Z0-9]/g, '')}`;

      const dueAt = new Date();
      dueAt.setDate(dueAt.getDate() + 30);

      const invoice = await prisma.invoice.create({
        data: {
          invoiceNumber,
          status: 'DRAFT',
          caseId,
          clientId: caseRecord.clientId,
          lineItems: JSON.parse(JSON.stringify(lineItems)),
          subtotal,
          vatRate,
          vatAmount,
          total,
          dueAt,
          notes: (actionParams.notes as string) || 'Generated by AI Plan Engine',
          createdById: caseRecord.assignedToId,
        },
      });

      logger.info(`[GENERATE_INVOICE] Case ${caseId}: invoice ${invoice.invoiceNumber} created, total R${total.toFixed(2)}`);
      return {
        success: true,
        result: {
          invoiceId: invoice.id,
          invoiceNumber: invoice.invoiceNumber,
          total: total.toFixed(2),
          status: 'DRAFT',
        },
      };
    } catch (err: unknown) {
      const message = err instanceof Error ? err.message : 'Unknown error';
      return { success: false, error: message };
    }
  },
);
