// Auto-generated exports
export * from './ActivityTab'
export * from './DocumentsTab'
export * from './NotificationBell'
export * from './PWAInstallPrompt'
export * from './ThemeSwitcher'
export * from './accounts/BatchHeaderActions'
export * from './accounts/BatchPaymentTable'
export * from './accounts/FileUploader'
export * from './cases/CommunicationHub'
export * from './cases/CompareAnalysisModal'
export * from './cases/NextUpdateCard'
export * from './cases/EditServicesModal'
export * from './cases/MoveCaseModal'
export * from './cases/SendPoaModal'
export * from './cases/WorkflowTimeline'
export * from './layout/DashboardSwitcher'
export * from './layout/GlobalAppSwitcher'
export * from './layout/MobileBottomNav'
export * from './layout/ProjectSwitcher'
export * from './layout/Sidebar'
export * from './layout/TopBar'
export * from './projects/DestinationPathSelector'
export * from './projects/MoveProjectModal'
export * from './projects/ProjectMembersModal'
export * from './providers/SessionProvider'
export * from './ui/DeleteConfirmationModal'
export * from './ui/Pagination'
export * from './ui/SignaturePad';
export * from './ui/RichTextEditor'
export * from './ui/SearchWithSuggestions'
export * from './providers/layout-context'
export * from './providers/project-context'
export * from './providers/theme-context'
export * from './plan/AIPlanTab'
export * from './plan/PlanStepCard'
export * from './plan/ConfidenceReport'
export * from './plan/InfoUpdatePanel'
export * from './plan/PlanDiffView'

export * from './cases/AIChatTab'

// Tier 1 Step 3 Additions
export * from './ui/Toaster'
export * from './ui/ConfirmDialog'
export * from './providers/ConfirmProvider'
export * from './ui/GlobalErrorBoundary'
